### ISSUE TITLE
[Feature/Improvement] Adaptive Material Icon

### ISSUE THREAD

**Issue by saltsoftdrink** [a-mabe/OpenHIIT#134]
Add material theme based adaptive app icon

**Comment by a-mabe** [comment]
Thank you for opening a feature request, your support is appreciated.

Adding context around the issue, the app is currently using [flutter_launcher_icons](https://github.com/fluttercommunity/flutter_launcher_icons) to generate the icons for iOS and Android. This package does allow for adaptive icons to be set:

- `adaptive_icon_background`: The color (E.g. "#ffffff") or image asset (E.g. "assets/images/christmas-background.png") which will be used to fill out the background of the adaptive icon.

- `adaptive_icon_foreground`: The image asset which will be used for the icon foreground of the adaptive icon Note: Adaptive Icons will only be generated when both adaptive_icon_background and adaptive_icon_foreground are specified. (the image_path is not automatically taken as foreground)

- `adaptive_icon_monochrome`: The image asset which will be used for the icon foreground of the Android 13+ themed icon. For more information see [Android Adaptive Icons](https://developer.android.com/develop/ui/views/launch/icon_design_adaptive#user-theming)

However the proper assets for adaptive icons **have not** been generated, so this is less of a programming task and more of a design task. Would be open to a full icon redesign in order to make this happen
